services:
    remnanode:
        container_name: remnanode
        hostname: remnanode
        image: remnawave/node:latest
        cap_add:
          - NET_ADMIN
        restart: always
        network_mode: host
        environment:
          - NODE_PORT=2222
          - SECRET_KEY="eyJub2RlQ2VydFBlbSI6Ii0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLVxuTUlJQmtUQ0NBVGlnQXdJQkFnSUhBWGRVQUVWSEF>
        volumes:
            - './geosite.dat:/usr/local/share/xray/geosite.dat'
            - './geoip.dat:/usr/local/share/xray/geoip.dat'
            - '/var/log/remnanode:/var/log/remnanode'