-- This migration originally created client_notifications and traffic_logs tables.
-- Both have been removed: client_notifications is unused, traffic_logs replaced by Remnawave bandwidth-stats API.
-- Migration kept as placeholder so Prisma doesn't try to re-apply it.
